[build]
  command = "python build_data.py"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.8"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/app/:splat"
  status = 200
  force = true

[[redirects]]
  from = "/test"
  to = "/.netlify/functions/test"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
