[build]
  command = "pip install -r requirements.txt"
  functions = "netlify/functions"
  publish = "."

[build.environment]
  PYTHON_VERSION = "3.9"

[[redirects]]
  from = "/api/turmas"
  to = "/.netlify/functions/app"
  status = 200
  force = true

[[redirects]]
  from = "/api/turma/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true

[[redirects]]
  from = "/api/series"
  to = "/.netlify/functions/app"
  status = 200
  force = true

[[redirects]]
  from = "/api/alunos/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true

[[redirects]]
  from = "/api/aluno/*/*"
  to = "/.netlify/functions/app"
  status = 200
  force = true

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
